server:
  port: 8889

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ghkdtlwns987/spring-cloud-config
        native:
          search-locations: file:\\D:\Coding\WEB\Spring\AMD\local_repo

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
